# Generated by Django 2.2.8 on 2020-07-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200623_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='news/%Y/%m-%d/')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='account.News')),
            ],
        ),
    ]
