# Generated by Django 2.2.8 on 2020-07-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200623_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('polls_id', models.IntegerField(default=0)),
            ],
        ),
    ]
