# Generated by Django 2.2.8 on 2020-07-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200723_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(default='')),
                ('date_begin', models.CharField(max_length=100)),
                ('date_end', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='conference/%Y/%m-%d/')),
            ],
            options={
                'verbose_name': 'конференция',
                'verbose_name_plural': 'конференции',
            },
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.AddField(
            model_name='polls',
            name='option_one',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='polls',
            name='option_one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='option_three',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='polls',
            name='option_three_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='option_two',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='polls',
            name='option_two_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls_questions',
            name='question',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='polls_comment',
            name='polls_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='polls_comment',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='polls_questions',
            name='polls_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='polls_secret',
            name='polls_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='polls_secret',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
