# Generated by Django 2.2.8 on 2020-07-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_post_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.AlterField(
            model_name='images',
            name='news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.News'),
        ),
    ]
