# Generated by Django 2.2.8 on 2020-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200728_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(default='')),
                ('date_begin', models.CharField(max_length=100)),
                ('date_end', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='conference/%Y/%m-%d/')),
            ],
            options={
                'verbose_name': 'конференция',
                'verbose_name_plural': 'конференции',
            },
        ),
        migrations.DeleteModel(
            name='Conferences',
        ),
    ]
