# Generated by Django 2.2.8 on 2020-07-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200728_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m-%d/')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.News')),
            ],
        ),
    ]
