# Generated by Django 2.2.8 on 2020-07-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200728_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='option_one_count',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='option_three_count',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='option_two',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='option_two_count',
        ),
        migrations.RemoveField(
            model_name='polls_questions',
            name='polls_id',
        ),
        migrations.RemoveField(
            model_name='polls_secret',
            name='polls_id',
        ),
        migrations.AddField(
            model_name='polls_questions',
            name='poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Polls'),
        ),
        migrations.AddField(
            model_name='polls_secret',
            name='poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Polls'),
        ),
    ]
